import devsim
devsim.add_2d_mesh(mesh="m1")
devsim.add_2d_mesh_line(mesh="m1", dir="y", pos=0, ps=1)
devsim.add_2d_mesh_line(mesh="m1", dir="y", pos=1, ps=1)
devsim.add_2d_mesh_line(mesh="m1", dir="x", pos=0, ps=1)
devsim.add_2d_mesh_line(mesh="m1", dir="x", pos=1, ps=1)
devsim.add_2d_region(mesh="m1", material="mat", region="reg")
devsim.finalize_mesh(mesh="m1")
devsim.create_device(mesh="m1", device="dev")
print("Edge models:", devsim.get_edge_model_list(device="dev", region="reg"))
print("Node models:", devsim.get_node_model_list(device="dev", region="reg"))
